hmpf, Krita does not compile at all. Errors everywhere :-(
e.g.
* tool_perspectivetransform includes kis_tool_non_paint.h ut there is no such file or
* histogramdocker.cc was missing an include and did contain an invalid forward-declaration and now
* koffice/libs/pigment/KoBasicHistogramProducers.h:43: error:   overriding 
‘virtual QList<KoChannelInfo*> KoBasicHistogramProducer::channels()’


svn path=/trunk/koffice/; revision=785724