Qt6: Make operator== const
Otherwise we get into trouble like this:

[100%] Building CXX object libs/resources/tests/CMakeFiles/TestResourceSearchBoxFilter.dir/TestResourceSearchBoxFilter.cpp.o
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qobject.h:13,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/QObject:1,
                 from /home/halla/dev/krita/libs/resources/tests/TestResourceSearchBoxFilter.h:10,
                 from /home/halla/dev/krita/libs/resources/tests/TestResourceSearchBoxFilter.cpp:7:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h: In instantiation of ‘qsizetype QtPrivate::indexOf(const QList<T>&, const U&, qsizetype) [with V = MockResource; U = MockResource; qsizetype = long long int]’:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:966:30:   required from ‘qsizetype QListSpecialMethodsBase<T>::indexOf(const AT&, qsizetype) const [with AT = MockResource; T = MockResource; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:48:31:   required from ‘bool QListSpecialMethodsBase<T>::contains(const AT&) const [with AT = MockResource; T = MockResource]’
/home/halla/dev/krita/libs/resources/tests/TestResourceSearchBoxFilter.cpp:204:9:   required from here
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:937:20: error: passing ‘const MockResource’ as ‘this’ argument discards qualifiers [-fpermissive]
  937 |             if (*n == u)
      |                 ~~~^~~~
/home/halla/dev/krita/libs/resources/tests/TestResourceSearchBoxFilter.h:24:10: note:   in call to ‘bool MockResource::operator==(MockResource&)’
   24 |     bool operator==(MockResource& rhs){
      |          ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:937:20: error: binding reference of type ‘MockResource&’ to ‘const MockResource’ discards qualifiers
  937 |             if (*n == u)
      |                 ~~~^~~~
/home/halla/dev/krita/libs/resources/tests/TestResourceSearchBoxFilter.h:24:35: note:   initializing argument 1 of ‘bool MockResource::operator==(MockResource&)’
   24 |     bool operator==(MockResource& rhs){
      |                     ~~~~~~~~~~~~~~^~~
make[3]: *** [libs/resources/tests/CMakeFiles/TestResourceSearchBoxFilter.dir/build.make:90: libs/resources/tests/CMakeFiles/TestResourceSearchBoxFilter.dir/TestResourceSearchBoxFilter.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:34222: libs/resources/tests/CMakeFiles/TestResourceSearchBoxFilter.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:34229: libs/resources/tests/CMakeFiles/TestResourceSearchBoxFilter.dir/rule] Error 2
make: *** [Makefile:358: libs/resources/tests/CMakeFiles/TestResourceSearchBoxFilter.dir/rule] Error 2