Buildfix: remove webp from ANDROID_EXTRA_LIBS
Only dynamic libraries need to be shipped with the APK, not archives.

Error: The file name of external library
/home/user/workspace/Krita_Nightly_Android_arm64-v8a_Build/build/i/lib/libwebp.a
must begin with "lib" and end with the suffix ".so".