Qt6: Fix building KoShapeReorderCommand
We need to use auto in places to paper over the differences between
Qt5 and Qt6, and pass nulltpr instead of 0 to avoid an error like

/home/halla/dev/krita/libs/flake/commands/KoShapeReorderCommand.cpp:168:24:   required from here
/usr/include/x86_64-linux-gnu/qt6/QtCore/qcontainertools_impl.h:375:40: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
  375 |     auto cmp = [&](auto &e) { return e == t;