Revert "[win] Make sure that already signed modules are not sent to the signer"
This reverts commit a8c04d2bb0afaada9f035ec1775a36a3bc8c330b.

Just to debug why we get an error while signing:

2026-05-20 15:44:31,547 ERROR signwindowsbinaries Error: SignWindowsBinariesJob failed
Traceback (most recent call last):
  File "C:\builds\graphics\krita\ci-notary-service\signwindowsbinaries.py", line 74, in signWindowsBinaries
    job.waitForCompletion()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\builds\graphics\krita\ci-notary-service\sftpnotary\windowsbinariessigner.py", line 115, in waitForCompletion
    self.extractSignedBinaries(self.localFilePath)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\builds\graphics\krita\ci-notary-service\sftpnotary\windowsbinariessigner.py", line 91, in extractSignedBinaries
    shutil.copyfile(extractPath / arcName, originalFilePath)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\Python-3.13\Lib\shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ~~~~^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\builds\\graphics\\krita\\krita-x64-6.1.0-prealpha-a8c04d2b\\bin\\libmlt++-7.dll'
2026-05-20 15:44:31,551 ERROR signwindowsbinaries Error: Signing Windows binaries failed