Revert "Fix brush outline jumps when switching between documents of different zoom"
This reverts commit f11a08cf018e187dd8a4871eff067ebaeee1b1fd.

This broke the build:

/home/boud/dev/krita/libs/ui/kis_zoom_manager.cc: In member function ‘void KisZoomManager::updateCurrentZoomResou
/home/boud/dev/krita/libs/ui/kis_zoom_manager.cc:231:85: error: ‘EffectiveZoom’ is not a member of ‘KisCanvasReso
  231 |     m_view->canvasBase()->resourceManager()->setResource(KisCanvasResourceProvider::EffectiveZoom, effect
      |                                                                                     ^~~~~~~~~~~~~
make[2]: *** [libs/ui/CMakeFiles/kritaui.dir/build.make:2003: libs/ui/CMakeFiles/kritaui.dir/kis_zoom_manager.cc.
make[1]: *** [CMakeFiles/Makefile2:21274: libs/ui/CMakeFiles/kritaui.dir/all] Error 2

CCMAIL:dimula73@gmail.com