Remove the Qt version override
It's no longer possible to build Krita with Qt < 5.6:

[ 26%] Building CXX object
libs/flake/CMakeFiles/kritaflake.dir/kritaflake_automoc.cpp.o
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:
In member function ‘qreal LayoutChunkWrapper::skipSpaceCharacter(int)’:
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:371:41:
error: ‘class QTextLayout’ has no member named ‘formats’
              formatForPos(pos, m_layout->formats());
                                          ^
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:
In member function ‘void KoSvgTextShape::relayout()’:
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:425:17:
error: ‘class QTextLayout’ has no member named ‘setFormats’
          layout->setFormats(chunk.formats);
                  ^
In file included from
/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h:37:0,
                  from
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:41,
                  from
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:40,
                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
                  from
/home/domain/farindk/prog/h265/krita/libs/flake/KoShapeFactoryBase.h:25,
                  from
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.h:24,
                  from
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:19:
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:487:66:
error: ‘const class QTextLayout’ has no member named ‘formats’
          Q_FOREACH (const QTextLayout::FormatRange &range,
layout.formats()) {
                                                                   ^
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:487:66:
error: ‘const class QTextLayout’ has no member named ‘formats’
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:487:9:
error: template argument 1 is invalid
          Q_FOREACH (const QTextLayout::FormatRange &range,
layout.formats()) {
          ^
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:487:9:
error: template argument 1 is invalid
          Q_FOREACH (const QTextLayout::FormatRange &range,
layout.formats()) {
          ^
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:487:9:
error: expected ‘::’ before ‘_container_’
          Q_FOREACH (const QTextLayout::FormatRange &range,
layout.formats()) {
          ^
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:487:66:
error: ‘const class QTextLayout’ has no member named ‘formats’
          Q_FOREACH (const QTextLayout::FormatRange &range,
layout.formats()) {
                                                                   ^
/home/domain/farindk/prog/h265/krita/libs/flake/text/KoSvgTextShape.cpp:487:9:
error: request for member ‘control’ in ‘_container_’, which is of
non-class type ‘int’
          Q_FOREACH (const QTextLayout::FormatRange &range,
layout.formats()) {
          ^