Revert "no need to malloc here we can use the constant provided by Vc"
This reverts commit bdc9f7f75d477e568e1de593c7a851c2c3b244ac.

This broke compilation on Windows, so revert for now:

M:/cm_msvc/git/calligra/krita/image/kis_brush_mask_applicator_factories.cpp(71) : error C2751: 'IndexesFromZero' :
the name of a function parameter cannot be qualified
u:\include\vc\scalar\../common/types.h(136) : fatal error C1903: unable to recover from previous error(s); stopping compilation
        u:\include\vc\scalar\../common/operators.h(36) : see reference to class template instantiation 'Vc::`anonymous-namespace'::HasImplicitCast<From,To>' being compiled
        with
        [
            From=overloaded-function,
            To=Vc::Scalar::short_v
        ]
        M:/cm_msvc/git/calligra/krita/image/kis_brush_mask_applicator_factories.cpp(92) : see reference to class template instantiation 'Vc::Scalar::`anonymous-namespace'::IsVectorOperands<T0,T1,V>' being compiled
        with
        [
            T0=overloaded-function,
            T1=Vc::float_v,
            V=Vc::Scalar::short_v
        ]
NMAKE : fatal error U1077: 'echo' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

CCMAIL: kretz@kde.org