Use kisBoundFast instead of qBound
To avoid, with Qt6,

home/halla/dev/krita/libs/pigment/KoColorSpaceMaths.h:296:41: error: call of overloaded ‘qBound<KoColorSpaceMaths<short int, short int>::dst_compositetype>(const qint16&, KoColorSpaceMaths<short int, short
                  int>::dst_compositetype&, const qint16&)’ is ambiguous
return qBound<dst_compositetype>(KoColorSpaceMathsTraits<_Tdst>::zeroValue, val, KoColorSpaceMathsTraits<_Tdst>::unitValue);