KoToolBase, KoShape, KoPatternBackground: Remove unused Q_Ds
libs/flake/KoShape.cpp:1496:28: error: unused variable 'd' [-Werror,-Wunused-variable]
libs/flake/KoToolBase.cpp:60:37: error: unused variable 'd' [-Werror,-Wunused-variable]
libs/flake/KoPatternBackground.cpp:144:40: error: unused variable 'd' [-Werror,-Wunused-variable]