Qt6: Store the histogram painters as pointers
I'm not 100% sure about this change. The issue is that QVector now
demands that its contents implement operator=, but because of how
we use a scoped shared pointer for the d-pointer that's kinda hard.

This was the error message:

n file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydatapointer.h:7,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/qbytearray.h:11,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/qcoreevent.h:8,
                 from /usr/include/x86_64-linux-gnu/qt6/QtGui/qevent.h:13:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydataops.h: In instantiation of ‘void QtPrivate::QGenericArrayOps<T>::Inserter::insertOne(qsizetype, T&&) [with T = KisHistogramPainter; qsizetype = long long int]’:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydataops.h:584:37:   required from ‘void QtPrivate::QGenericArrayOps<T>::emplace(qsizetype, Args&& ...) [with Args = {KisHistogramPainter}; T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:886:15:   required from ‘T& QList<T>::emplaceBack(Args&& ...) [with Args = {KisHistogramPainter}; T = KisHistogramPainter; reference = KisHistogramPainter&]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:467:24:   required from ‘void QList<T>::append(rvalue_ref) [with T = KisHistogramPainter; rvalue_ref = KisHistogramPainter&&]’
/home/halla/dev/krita/libs/ui/widgets/KisHistogramView.cpp:61:38:   required from here
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydataops.h:499:29: error: use of deleted function ‘KisHistogramPainter& KisHistogramPainter::operator=(const KisHistogramPainter&)’
  499 |                     last[i] = std::move(last[i - 1]);
      |                     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/halla/dev/krita/libs/ui/widgets/KisHistogramView.cpp:13:
/home/halla/dev/krita/libs/ui/widgets/KisHistogramPainter.h:27:22: note: ‘KisHistogramPainter& KisHistogramPainter::operator=(const KisHistogramPainter&)’ is implicitly declared as deleted because ‘KisHistogramPainter’ declares a move constructor or move assignment operator
   27 | class KRITAUI_EXPORT KisHistogramPainter
      |                      ^~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydataops.h:502:24: error: use of deleted function ‘KisHistogramPainter& KisHistogramPainter::operator=(const KisHistogramPainter&)’
  502 |                 *where = std::move(t);
      |                 ~~~~~~~^~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydataops.h:9:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qcontainertools_impl.h: In instantiation of ‘void QtPrivate::q_relocate_overlap_n_left_move(iterator, N, iterator) [with iterator = KisHistogramPainter*; N = long long int]’:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qcontainertools_impl.h:248:43:   required from ‘void QtPrivate::q_relocate_overlap_n(T*, N, T*) [with T = KisHistogramPainter; N = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydatapointer.h:316:40:   required from ‘void QArrayDataPointer<T>::relocate(qsizetype, const T**) [with T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydatapointer.h:301:9:   required from ‘bool QArrayDataPointer<T>::tryReadjustFreeSpace(QArrayData::GrowthPosition, qsizetype, const T**) [with T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydatapointer.h:202:26:   required from ‘void QArrayDataPointer<T>::detachAndGrow(QArrayData::GrowthPosition, qsizetype, const T**, QArrayDataPointer<T>*) [with T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydataops.h:576:28:   required from ‘void QtPrivate::QGenericArrayOps<T>::emplace(qsizetype, Args&& ...) [with Args = {KisHistogramPainter}; T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:886:15:   required from ‘T& QList<T>::emplaceBack(Args&& ...) [with Args = {KisHistogramPainter}; T = KisHistogramPainter; reference = KisHistogramPainter&]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:467:24:   required from ‘void QList<T>::append(rvalue_ref) [with T = KisHistogramPainter; rvalue_ref = KisHistogramPainter&&]’
/home/halla/dev/krita/libs/ui/widgets/KisHistogramView.cpp:61:38:   required from here
/usr/include/x86_64-linux-gnu/qt6/QtCore/qcontainertools_impl.h:213:18: error: use of deleted function ‘KisHistogramPainter& KisHistogramPainter::operator=(const KisHistogramPainter&)’
  213 |         *d_first = std::move_if_noexcept(*first);
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt6/QtCore/qcontainertools_impl.h: In instantiation of ‘void QtPrivate::q_relocate_overlap_n_left_move(iterator, N, iterator) [with iterator = std::reverse_iterator<KisHistogramPainter*>; N = long long int]’:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qcontainertools_impl.h:252:43:   required from ‘void QtPrivate::q_relocate_overlap_n(T*, N, T*) [with T = KisHistogramPainter; N = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydatapointer.h:316:40:   required from ‘void QArrayDataPointer<T>::relocate(qsizetype, const T**) [with T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydatapointer.h:301:9:   required from ‘bool QArrayDataPointer<T>::tryReadjustFreeSpace(QArrayData::GrowthPosition, qsizetype, const T**) [with T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydatapointer.h:202:26:   required from ‘void QArrayDataPointer<T>::detachAndGrow(QArrayData::GrowthPosition, qsizetype, const T**, QArrayDataPointer<T>*) [with T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydataops.h:576:28:   required from ‘void QtPrivate::QGenericArrayOps<T>::emplace(qsizetype, Args&& ...) [with Args = {KisHistogramPainter}; T = KisHistogramPainter; qsizetype = long long int]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:886:15:   required from ‘T& QList<T>::emplaceBack(Args&& ...) [with Args = {KisHistogramPainter}; T = KisHistogramPainter; reference = KisHistogramPainter&]’
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlist.h:467:24:   required from ‘void QList<T>::append(rvalue_ref) [with T = KisHistogramPainter; rvalue_ref = KisHistogramPainter&&]’
/home/halla/dev/krita/libs/ui/widgets/KisHistogramView.cpp:61:38:   required from here
/usr/include/x86_64-linux-gnu/qt6/QtCore/qcontainertools_impl.h:213:18: error: use of deleted function ‘KisHistogramPainter& KisHistogramPainter::operator=(const KisHistogramPainter&)’
make[2]: *** [libs/ui/CMakeFiles/kritaui.dir/build.make:3968: libs/ui/CMakeFiles/kritaui.dir/widgets/KisHistogramView.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:27935: libs/ui/CMakeFiles/kritaui.dir/all] Error 2