Fix building with Qt > 5.12
Probably; not sure when these definitions were added to qhashfunctions.h.

In file included from /home/boud/dev/resources/libs/resources/KisResourcesInterface.cpp:23:0:
/home/boud/dev/resources/libs/resources/KisResourcesInterface_p.h:35:23: error: redefinition of ‘struct std::hash<QString>’
     template<> struct hash<QString>
                       ^~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:47:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QImage:1,
                 from /home/boud/dev/resources/libs/resources/KoResource.h:22,
                 from /home/boud/dev/resources/libs/resources/KisResourcesInterface.h:24,
                 from /home/boud/dev/resources/libs/resources/KisResourcesInterface.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h:204:1: note: previous definition of ‘struct std::hash<QString>’
 QT_SPECIALIZE_STD_HASH_TO_CALL_QHASH_BY_CREF(QString)
 ^
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
libs/resources/CMakeFiles/kritaresources.dir/build.make:830: recipe for target 'libs/resources/CMakeFiles/kritaresources.dir/KisResourcesInterface.cpp.o' failed
make[2]: *** [libs/resources/CMakeFiles/kritaresources.dir/KisResourcesInterface.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....