Qt6: ifdef between qreal* and float* for QColor
Qt6 QColor now uses float* in its api instead of qreal*, while
keeping qreal a double. This breaks:

/home/halla/dev/krita/libs/widgets/kis_color_input.cpp: In member function ‘void KisHsvColorInput::getHsxF(const QColor&, qreal*, qreal*, qreal*)’:
/home/halla/dev/krita/libs/widgets/kis_color_input.cpp:684:23: error: cannot convert ‘qreal*’ {aka ‘double*’} to ‘float*’
  684 |         color.getHslF(&tempH, s, x);
      |                       ^~~~~~
      |                       |
      |                       qreal* {aka double*}
In file included from /usr/include/x86_64-linux-gnu/qt6/QtGui/qpixmap.h:9,
                 from /usr/include/x86_64-linux-gnu/qt6/QtGui/qicon.h:10,
                 from /usr/include/x86_64-linux-gnu/qt6/QtGui/qaction.h:11,
                 from /usr/include/x86_64-linux-gnu/qt6/QtWidgets/qwidget.h:12,
                 from /usr/include/x86_64-linux-gnu/qt6/QtWidgets/QWidget:1,
                 from /home/halla/dev/krita/libs/widgets/kis_color_input.h:10,
                 from /home/halla/dev/krita/libs/widgets/kis_color_input.cpp:9:
/usr/include/x86_64-linux-gnu/qt6/QtGui/qcolor.h:158:25: note:   initializing argument 1 of ‘void QColor::getHslF(float*, float*, float*, float*) const’
  158 |     void getHslF(float *h, float *s, float *l, float *a = nullptr) const;
      |                  ~~~~~~~^
/home/halla/dev/krita/libs/widgets/kis_color_input.cpp:699:31: error: cannot convert ‘qreal*’ {aka ‘double*’} to ‘float*’
  699 |                 color.getHsvF(&tempH, s, x);
      |                               ^~~~~~
      |                               |
      |                               qreal* {aka double*}
/usr/include/x86_64-linux-gnu/qt6/QtGui/qcolor.h:128:25: note:   initializing argument 1 of ‘void QColor::getHsvF(float*, float*, float*, float*) const’
  128 |     void getHsvF(float *h, float *s, float *v, float *a = nullptr) const;
      |                  ~~~~~~~^
/home/halla/dev/krita/libs/widgets/kis_color_input.cpp: In constructor ‘KisHsvColorInput::KisHsvColorInput(QWidget*, KoColor*)’:
/home/halla/dev/krita/libs/widgets/kis_color_input.cpp:458:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
  458 |             m_hInput = input;
      |             ~~~~~~~~~^~~~~~~
/home/halla/dev/krita/libs/widgets/kis_color_input.cpp:459:9: note: here
  459 |         case 1:
      |         ^~~~
/home/halla/dev/krita/libs/widgets/kis_color_input.cpp:461:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
  461 |             m_sInput = input;
      |             ~~~~~~~~~^~~~~~~
/home/halla/dev/krita/libs/widgets/kis_color_input.cpp:462:9: note: here
  462 |         case 2:
      |
So use temporary float instead of qreal.