Fix missing include
In file included from /srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/qlist.h:47:0,
                 from /srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/qvariant.h:47,
                 from /srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/QVariant:1,
                 from /srv/jenkins/install/linux/x86_64/g++/qt4/kde/kdelibs/KDE/4.12/include/kconfiggroup.h:32,
                 from /srv/jenkins/install/linux/x86_64/g++/qt4/kde/kdelibs/KDE/4.12/include/kdialog.h:32,
                 from /srv/jenkins/workspace/calligra_master/build/plugins/textshape/ui_SimpleCitationBibliographyWidget.h:1,
                 from /srv/jenkins/workspace/calligra_master/plugins/textshape/dialogs/SimpleCitationBibliographyWidget.h:22,
                 from /srv/jenkins/workspace/calligra_master/plugins/textshape/dialogs/SimpleCitationBibliographyWidget.cpp:19:
/srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/qalgorithms.h: In instantiation of ‘void qDeleteAll(ForwardIterator, ForwardIterator) [with ForwardIterator = QList<KoBibliographyInfo*>::iterator]’:
/srv/jenkins/workspace/calligra_master/plugins/textshape/dialogs/SimpleCitationBibliographyWidget.cpp:71:60:   required from here
/srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/qalgorithms.h:322:9: error: possible problem detected in invocation of delete operator: [-Werror]
/srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/qalgorithms.h:322:9: error: invalid use of incomplete type ‘class KoBibliographyInfo’ [-Werror]
In file included from /srv/jenkins/workspace/calligra_master/plugins/textshape/dialogs/SimpleCitationBibliographyWidget.cpp:19:0:
/srv/jenkins/workspace/calligra_master/plugins/textshape/dialogs/SimpleCitationBibliographyWidget.h:31:7: error: forward declaration of ‘class KoBibliographyInfo’ [-Werror]
In file included from /srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/qlist.h:47:0,
                 from /srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/qvariant.h:47,
                 from /srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/QVariant:1,
                 from /srv/jenkins/install/linux/x86_64/g++/qt4/kde/kdelibs/KDE/4.12/include/kconfiggroup.h:32,
                 from /srv/jenkins/install/linux/x86_64/g++/qt4/kde/kdelibs/KDE/4.12/include/kdialog.h:32,
                 from /srv/jenkins/workspace/calligra_master/build/plugins/textshape/ui_SimpleCitationBibliographyWidget.h:1,
                 from /srv/jenkins/workspace/calligra_master/plugins/textshape/dialogs/SimpleCitationBibliographyWidget.h:22,
                 from /srv/jenkins/workspace/calligra_master/plugins/textshape/dialogs/SimpleCitationBibliographyWidget.cpp:19:
/srv/jenkins/install/linux/x86_64/g++/qt4/qt/4.8/include/QtCore/qalgorithms.h:322:9: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined