Use ecm's sip generation instead of manually created sip files
We still generate from our wrapper library, not from krita's
own libraries. It doesn't work yet -- the generator breask on
tr:

[ 93%] Generating sip/krita/PyKrita/Action.sip
_fn_get qt_check_for_QOBJECT_macro
_fn_get metaObject
_fn_get qt_metacast
_fn_get qt_metacall
_fn_get tr
Traceback (most recent call last):
  File "/home/boud/dev/deps/share/ECM/find-modules/sip_generator.py", line 688, in main
    body, includes = g.create_sip(args.source, args.include_filename)
  File "/home/boud/dev/deps/share/ECM/find-modules/sip_generator.py", line 127, in create_sip
    body = self._container_get(self.tu.cursor, -1, h_file, include_filename)
  File "/home/boud/dev/deps/share/ECM/find-modules/sip_generator.py", line 202, in _container_get
    decl = self._container_get(member, level + 1, h_file, include_filename)
  File "/home/boud/dev/deps/share/ECM/find-modules/sip_generator.py", line 180, in _container_get
    decl = self._fn_get(container, member, level + 1)
  File "/home/boud/dev/deps/share/ECM/find-modules/sip_generator.py", line 392, in _fn_get
    "init": self._fn_get_parameter_default(function, child),
  File "/home/boud/dev/deps/share/ECM/find-modules/sip_generator.py", line 549, in _fn_get_parameter_default
    return _get_param_value(text, parameterType)
  File "/home/boud/dev/deps/share/ECM/find-modules/sip_generator.py", line 500, in _get_param_value
    if not "::" in parameterType.spelling:
TypeError: argument of type 'NoneType' is not iterable

plugins/extensions/pykrita/CMakeFiles/generate_PyKrita_sip_files.dir/build.make:88: recipe for target 'plugins/extensions/pykrita/sip/krita/PyKrita/Action.sip' failed
make[2]: *** [plugins/extensions/pykrita/sip/krita/PyKrita/Action.sip] Error 255

Even though the rules_PyKrita file inherits Qt5Ruleset, which should
cause generator to skip tr().