Revert "Remove BUILD_IN_SOURCE option for Qt on non-windows systems as well"
My local logs show that compiling outside of source causes the
following:

duplicate symbol 'QMutexPrivate::wakeUp()' in:
    .obj/debug/qmutex.o
    .obj/debug/qmutex_mac.o
duplicate symbol 'QMutexPrivate::~QMutexPrivate()' in:
    .obj/debug/qmutex.o
    .obj/debug/qmutex_mac.o
duplicate symbol 'QMutexPrivate::QMutexPrivate()' in:
    .obj/debug/qmutex.o
    .obj/debug/qmutex_mac.o
duplicate symbol 'QMutexPrivate::~QMutexPrivate()' in:
    .obj/debug/qmutex.o
    .obj/debug/qmutex_mac.o
duplicate symbol 'QMutexPrivate::QMutexPrivate()' in:
    .obj/debug/qmutex.o
    .obj/debug/qmutex_mac.o
duplicate symbol 'QMutexPrivate::wait(int)' in:
    .obj/debug/qmutex.o
    .obj/debug/qmutex_mac.o
ld: 6 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[8]: *** [../../lib/QtCore.framework/QtCore_debug] Error 1
make[7]: *** [debug-all] Error 2

This reverts commit f8ae50561c18864fa69cd2eda7f41fcfa44695eb.

CCMAIL: kimageshop@kde.org