KoStreamedMath: clearPixel, copyPixel: Fail at link time instead of runtime when unimplmemented specialization is used.
This makes it easier to catch errors.

libs/pigment/compositeops/KoStreamedMath.h:389:67: error: unused parameter 'dst' [-Werror,-Wunused-parameter]