Revert "Improved convertToPaintLayer to use KisProcessingApplicator"
This reverts commit f2fee32ebb88595ad7ee4621810b4b095515a85c.

It fails compilation on Windows for some reason:

C:/dev/env-5/krita/libs/image/kis_layer_utils.cpp: In function 'void KisLayerUtils::mergeDown(KisImageSP, KisLayerSP, const KisMetaData::MergeStrategy*)':
C:/dev/env-5/krita/libs/image/kis_layer_utils.cpp:1317:72: error: call of overloaded 'RefreshDelayedUpdateLayers(KisLayerUtils::MergeDownInfoSP&)' is ambiguous
             applicator.applyCommand(new RefreshDelayedUpdateLayers(info), KisStrokeJobData::BARRIER);
                                                                        ^
C:/dev/env-5/krita/libs/image/kis_layer_utils.cpp:468:9: note: candidate: KisLayerUtils::RefreshDelayedUpdateLayers::RefreshDelayedUpdateLayers(KisLayerUtils::ConvertToPaintLayerInfoSP)
         RefreshDelayedUpdateLayers(ConvertToPaintLayerInfoSP info){
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
C:/dev/env-5/krita/libs/image/kis_layer_utils.cpp:465:9: note: candidate: KisLayerUtils::RefreshDelayedUpdateLayers::RefreshDelayedUpdateLayers(KisLayerUtils::MergeDownInfoBaseSP)
         RefreshDelayedUpdateLayers(MergeDownInfoBaseSP info)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~